public class TrainingAssignment {
    
    public static void QuestionOne(){
        //Create a variable isApproved of type Boolean and set it to true.
        Boolean isApproved =True;
        //Write an if-else statement that prints "Access granted" if the Boolean variable isApproved is true, and "Access denied" otherwise.
        if(isApproved == True){
            System.debug('Access Granted');
        }else{
            System.debug('Access Denied');
        }
    }
    
    public static void QuestionTwo(){
        //Using a for loop, iterate through numbers 1 to 5 and print each number
        for(Integer i=0;i<5;i++){
            System.debug(i + 1);
        }  
    }
    public static void QuestionThree(){
    //Create a List of Strings containing the names "John", "Jane", and "Bob"
    
    }
}